name: Deno

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
            deno-version: v1.x
      - uses: actions/checkout@v3

      - name: Lint
        run: deno lint

      - name: Check format
        run: deno fmt --check *.ts events/*

      - name: Run tests
        run: deno test --allow-read
